services:
  - type: web
    name: laravel-webhook
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: all_provider_transactions
          property: connectionString
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: all_provider_transactions
    plan: free
